sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t seanveal/docker-react -f Dockerfile.dev .

script:
  - docker run seanveal/docker-react npm run test -- --coverage